### ISSUE TITLE
TrelloScrum is not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by jery-v** [Q42/TrelloScrum#115] opened 2017-11-20 14:41 UTC
TrelloScrum is not compatible with Firefox Quantum

**Comment by cadesalaberry** [comment] 2017-11-20 21:17
I would love to see an update as well 👍

**Comment by Patribu** [comment] 2017-11-21 08:18
+1

**Comment by watsonalexander** [comment] 2017-11-21 10:00
Hi,

would be great to update the scoring plugin for trello!!! Thanks!

**Comment by cadesalaberry** [comment] 2017-11-29 08:21
I found a temporary solution using https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/

**Comment by SeanColombo** [comment] 2017-12-17 21:07
I've submitted a version 1.101 to Mozilla Add-ons which will make it a WebExtension that's compatible with Quantum (FF 57+).

**Comment by SeanColombo** [comment] 2017-12-17 21:12
I guess this is a duplicate of #113 so I'm going to close this one and follow-up there as the extension hopefully gets approved/released.

**Closed by SeanColombo** 2017-12-17 21:12 UTC
